# Generated by Django 3.0.4 on 2020-03-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
